# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-04 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='Idc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='manufacturer',
        ),
    ]
