# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190904_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, max_length=30, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=15, verbose_name='子网掩码')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='网卡设备', max_length=20, verbose_name='网卡设备')),
                ('mac_address', models.CharField(help_text='Mac_address', max_length=30, verbose_name='Mac_address')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'resource_network_device',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, help_text='os', max_length=50, null=True, verbose_name='os'),
        ),
        migrations.AddField(
            model_name='networkdevicemodel',
            name='host',
            field=models.ForeignKey(help_text='所在服务器', on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='所在服务器'),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='device',
            field=models.ForeignKey(help_text='所在网卡', on_delete=django.db.models.deletion.CASCADE, to='servers.NetworkDeviceModel', verbose_name='所在网卡'),
        ),
    ]
