# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20190905_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='manufacturer',
            field=models.ForeignKey(default=1, help_text='厂商', on_delete=django.db.models.deletion.CASCADE, to='servers.Manufacturer', verbose_name='厂商'),
        ),
    ]
