# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk',
            field=models.CharField(blank=True, help_text='disk', max_length=50, null=True, verbose_name='disk'),
        ),
    ]
