# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20190905_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='rmt_card_ip',
            field=models.CharField(blank=True, help_text='远程管理卡IP', max_length=15, null=True, unique=True, verbose_name='远程管理卡IP'),
        ),
    ]
