# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20190905_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'),)},
        ),
    ]
