# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'permissions': (('view_idc', 'can view idc'),)},
        ),
    ]
